version: '3.8'

name: 42inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
      args:
        CERTIFICATE: ${CERTIFICATE}
        VALUE_: ${VALUE_}
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wp-volume:/var/www/
    restart: always 

  wordpress:
    container_name: wp
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
    env_file:
      - .env
    networks:
      - inception
    restart: always 
    volumes:
      - wp-volume:/var/www/
    depends_on:
      - mariadb


  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DBR_PASS: ${DBR_PASS}
        DB_HOST: ${DB_HOST}
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
